# Generated by Django 6.0.2 on 2026-02-26 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50)),
                ('house_type', models.CharField(choices=[('Single Room', 'Single Room'), ('Bedsitter', 'Bedsitter'), ('1 Bedroom', '1 Bedroom'), ('2 Bedroom', '2 Bedroom')], max_length=50)),
                ('rent', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Vacant', 'Vacant'), ('Occupied', 'Occupied')], default='Vacant', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_units', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
