# Generated by Django 6.0.2 on 2026-02-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='landlord',
        ),
    ]
